<h1>Data Validation Code</h1>

In [7]:
import numpy as np # imports a fast numerical programming library
import scipy as sp #imports stats functions, amongst other things
import pandas as pd #lets us handle data as dataframes

from sklearn.metrics import mean_squared_error
import math

<b> Retrieve dataframes from .csv files </b>

In [8]:
df_1 = pd.read_csv('./active_generated.csv')
df_2 = pd.read_csv('./inactive_generated.csv')

df_sal_age = pd.read_csv('./data/act_sal_age.csv')
df_age_lev = pd.read_csv('./data/act_age_lev.csv')
df_sal_age.columns = ["0_0", "21_29", "30_39", "40_49", "50_59", "60_69", "70_79", "80_89", "90_100", "sum_sal"]
df_sal_age.head(5)

,0_0,21_29,30_39,40_49,50_59,60_69,70_79,80_89,90_100,sum_sal
0,1000_4999,0.0019,0.0014,0.0013,0.0021,0.0015,0.0000,0.0000,0.0,0.0083
1,5000_9999,0.0153,0.0062,0.0057,0.0089,0.0065,0.0038,0.0022,0.0,0.0486
2,10000_24999,0.0185,0.0095,0.0087,0.0137,0.0100,0.0058,0.0034,0.0,0.0696
3,25000_49999,0.0145,0.0112,0.0102,0.0161,0.0118,0.0068,0.0040,0.0,0.0745
4,50000_99999,0.0327,0.0252,0.0231,0.0364,0.0266,0.0153,0.0091,0.0,0.1683

In [9]:
sal_arr = df_sal_age.iloc[0:-1, 0].to_numpy()
age_arr = df_sal_age.columns[1:-1]
age_arr

Index(['21_29', '30_39', '40_49', '50_59', '60_69', '70_79', '80_89',
       '90_100'],
      dtype='object')

<b> Print out percentages of the ranges that are calculated based upon the generated data and Mean Square Error (MSE) between the original percentage and the generated data's percentage. We can see that the MSE is around E^-8, which are fairly small to prove the faithfulness to the original dataset.

In [10]:
count = 0
def srange(s):
    range_age = s.split('_')
    floor = int(range_age[0])
    ceiling = int(range_age[1])
    return floor, ceiling

In [11]:
for k in range(8):
    print("--------")
    column_ = list()
    floor_a, ceiling_a = srange(age_arr[k])
    for j in range(14):
        c = 0
        for index, i in df_1.iterrows():
            if (i["Age"] >= floor_a and i["Age"] <= ceiling_a):
                floor, ceiling = srange(sal_arr[j])
                if (i["Balance"] >= floor and i["Balance"] <= ceiling):
                    c += 1
        column_.append(c/1234)
        print(c/1234)
    print("mean square error (MSE): ") 
    cur = df_sal_age.iloc[0:-1, k+1].to_numpy()
    err = mean_squared_error(cur, column_)
    print(err)

--------
0.0016207455429497568
0.01539708265802269
0.018638573743922204
0.014586709886547812
0.03241491085899514
0.02593192868719611
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
mean square error (MSE):
1.5200741287507654e-08
--------
0.0016207455429497568
0.006482982171799027
0.009724473257698542
0.011345218800648298
0.025121555915721232
0.03970826580226904
0.03241491085899514
0.0
0.0
0.0
0.0
0.0
0.0
0.0
mean square error (MSE):
3.4179371387893286e-08
--------
0.0016207455429497568
0.005672609400324149
0.008914100486223663
0.01053484602917342
0.023500810372771474
0.03646677471636953
0.029983792544570502
0.023500810372771474
0.0
0.0
0.0
0.0
0.0
0.0
mean square error (MSE):
1.5176711173687707e-07
--------
0.0024311183144246355
0.008914100486223663
0.013776337115072933
0.01620745542949757
0.03646677471636953
0.05753646677471637
0.04700162074554295
0.03889789303079417
0.028363047001620744
0.0
0.0
0.0
0.0
0.0
mean square error (MSE):
4.21750900528852e-08
--------
0.0016207455429497568
0.006482982171799027
0.009724473257698542
0.012155591572123177
0.02674230145867099
0.04213938411669368
0.03484602917341977
0.028363047001620744
0.02106969205834684
0.007293354943273906
0.0
0.0
0.0
0.0
mean square error (MSE):
2.3295372713309752e-08
--------
0.0
0.004051863857374392
0.005672609400324149
0.006482982171799027
0.01539708265802269
0.024311183144246355
0.02025931928687196
0.01620745542949757
0.012155591572123177
0.004051863857374392
0.005672609400324149
0.0
0.0
0.0
mean square error (MSE):
3.4257740570386896e-08
--------
0.0
0.0024311183144246355
0.0032414910858995136
0.004051863857374392
0.008914100486223663
0.014586709886547812
0.012155591572123177
0.009724473257698542
0.007293354943273906
0.0024311183144246355
0.0032414910858995136
0.0024311183144246355
0.0
0.0
mean square error (MSE):
3.817337774403786e-08
--------
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
mean square error (MSE):
0.0